version: '3'

services:
  etcd:
    image: ccr.ccs.tencentyun.com/zhuyst/etcd:v3.2.25
    volumes:
      - /data/etcd:/etcd_data
    ports:
      - 2379:2379
      - 2380:2380
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd=http://etcd:2380
      - -initial-cluster-state
      - new
  e3w:
    image: soyking/e3w:latest
    volumes:
      - ./e3w/config.default.ini:/app/conf/config.default.ini
    ports:
      - 8080:8080
    depends_on:
      - etcd